name: Update Visit Counter

on:
  push:
    branches:
      - main

jobs:
  update_counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update visit count
        run: |
          if [ ! -f counter.txt ]; then echo 0 > counter.txt; fi
          count=$(cat counter.txt)
          new_count=$((count + 1))
          echo $new_count > counter.txt

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          git add counter.txt
          
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update visit count [skip ci]" || echo "No changes to commit"
            git push origin main || echo "Push failed"
          fi
